version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: testcafe
    versions:
    - 1.10.1
    - 1.11.0
    - 1.12.0
    - 1.13.0
