version: '3.4'

services:

  client:
    container_name: client
    build:
      context: https://github.com/dmmeteo/flask-microservices-client.git
      dockerfile: Dockerfile-prod
    ports:
      - 80
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users

  users:
    container_name: users
    build: 
      context: https://github.com/dmmeteo/flask-microservices-users.git
      dockerfile: Dockerfile-prod
    ports:
      - 5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build: 
      context: https://github.com/dmmeteo/flask-microservices-users.git#master:project/db
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users

  swagger:
    container_name: swagger
    build:
      context: https://github.com/dmmeteo/flask-microservices-swagger.git
    ports:
      - 8080:8080
    environment:
      - API_URL=https://raw.githubusercontent.com/dmmeteo/flask-microservices-swagger/master/swagger.json
    depends_on:
      - users






