version: '3'

services:

  client:
    container_name: client
    build:
      context: ../flask-microservices-client
      dockerfile: Dockerfile-local
    volumes:
      - ../flask-microservices-client:/usr/src/app
    ports:
      - 3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users

  users:
    container_name: users
    build: 
      context: ../flask-microservices-users
      dockerfile: Dockerfile-local
    volumes:
        - ../flask-microservices-users:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build: 
      context: ../flask-microservices-users/project/db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  swagger:
    container_name: swagger
    build:
      context: ../flask-microservices-swagger
    ports:
      - 8080:8080
    environment:
      - API_URL=https://raw.githubusercontent.com/dmmeteo/flask-microservices-swagger/master/swagger.json
    depends_on:
      - users

  eval:
    container_name: eval
    build:
      context: ../flask-microservices-eval
      dockerfile: Dockerfile-local
    volumes:
      - ../flask-microservices-eval:/usr/src/app
    ports:
      - 5002:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - USERS_SECRET_URL=http://users:5000
      - DATABASE_URL=postgresql://postgres:postgres@eval-db:5432/eval_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@eval-db:5432/eval_test
    depends_on:
      - users
      - eval-db

  eval-db:
    container_name: eval-db
    restart: always
    build:
      context: ../flask-microservices-eval/project/db
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


