version: '3.4'

services:

  client:
    container_name: client
    build:
      context: ../flask-microservices-client
      dockerfile: Dockerfile-dev
    volumes:
      - ../flask-microservices-client:/usr/src/app
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users
    links:
      - users

  users:
    container_name: users
    build: 
      context: ../flask-microservices-users
      dockerfile: Dockerfile-dev
    volumes:
        - ../flask-microservices-users:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db

  users-db:
    container_name: users-db
    build: 
      context: ../flask-microservices-users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  swagger:
    container_name: swagger
    build:
      context: ../flask-microservices-swagger
    ports:
      - 8080:8080
    environment:
      - API_URL=https://raw.githubusercontent.com/dmmeteo/flask-microservices-swagger/master/swagger.json
    depends_on:
      - users




