version: '3'

services:

  client:
    container_name: client
    build:
      context: https://github.com/dmmeteo/flask-microservices-client.git
      dockerfile: Dockerfile-stage
    ports:
      - 80
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users

  users:
    container_name: users
    build: 
      context: https://github.com/dmmeteo/flask-microservices-users.git
      dockerfile: Dockerfile-stage
    ports:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_stage
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    build: 
      context: https://github.com/dmmeteo/flask-microservices-users.git#master:project/db
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  swagger:
    container_name: swagger
    build:
      context: https://github.com/dmmeteo/flask-microservices-swagger.git
    ports:
      - 8080:8080
    environment:
      - API_URL=https://raw.githubusercontent.com/dmmeteo/flask-microservices-swagger/master/swagger.json
    depends_on:
      - users

  # eval:
  #   container_name: eval
  #   build: 
  #     context: https://github.com/dmmeteo/flask-microservices-eval.git
  #     dockerfile: Dockerfile-stage
  #   volumes:
  #     - ../flask-microservices-eval:/usr/src/app
  #   ports:
  #     - 5002:5000
  #   environment:
  #     - FLASK_APP=project/__init__.py
  #     - FLASK_DEBUG=1
  #     - APP_SETTINGS=project.config.DevelopmentConfig
  #     - USERS_SECRET_URL=http://users:5000
  #     - DATABASE_URL=postgresql://postgres:postgres@eval-db:5432/eval_dev
  #     - DATABASE_TEST_URL=postgresql://postgres:postgres@eval-db:5432/eval_test
  #   depends_on:
  #     - users
  #     - eval-db

  # eval-db:
  #   container_name: eval-db
  #   restart: always
  #   build: 
  #     context: https://github.com/dmmeteo/flask-microservices-eval.git#master:project/db
  #   ports:
  #     - 5436:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres


